#!/bin/bash

DIR_ROOT="/var/www/html/ginkgo"

dir=$1
inFile=$2
statFile=$3 
doStep1=$4
doStep2=$5
doStep3=$6
binMeth=$7
segMeth=$8
clustMeth=$9
distMet=$10

total=`wc -l < ${dir}/${inFile}`

if (( doStep1 == 1 )); then
  cnt=0;
  while read file; do
    ./status ${dir}/${statFile} 1 $file $cnt $total  
    ./bin_unsorted $DIR_ROOT/bins_${binMeth} `wc -l < $DIR_ROOT/bins_${binMeth}` ${dir}/${file} `echo ${file} | awk -F "." '{print $1}'` ${dir}/${file}_mapped
    cnt=$(($cnt+1));
  done < ${dir}/${inFile}

  paste bins_${binMeth} ${dir}/*_mapped > ${dir}/data
  ./status ${dir}/${statFile} 1 done $cnt $total

fi

if (( doStep2 == 1 )); then
  ./status ${dir}/${statFile} 2 initializing 0 1
  rm ${dir}/*jpeg ${dir}/hist.newick ${dir}/SegFile -f
  ./finish.R $DIR_ROOT ${dir} ${statFile} data ${binMeth} ${segMeth} ${ClustMeth} ${DistMet}
fi

if (( doStep3 == 1 )); then
  ./status ${dir}/${statFile} 4 recomputing_histogram 0 1
  ./fix.R $DIR_ROOT ${dir} ${statFile} SegFile ${ClustMeth} ${DistMet}
fi

