#!/bin/bash

/opt/hpc/bin/bwa aln -t 4 ${ASSEMBLY}.fa ${IN}_${LENGTH}_frags > ${TMPDIR}/${IN}_${LENGTH}_frags.sai

/opt/hpc/bin/bwa samse -n 1 ${ASSEMBLY}.fa ${TMPDIR}/${IN}_${LENGTH}_frags.sai ${IN}_${LENGTH}_frags | grep "NM:i:0" | awk '{print $3"\t"$4}' | grep -w $IN | sort -k2,2g > ${IN}_${LENGTH}_bwa_done

rm ${TMPDIR}/${IN}_${LENGTH}_frags.sai

for size in `cat binsizes`; do
  /opt/uge/bin/lx-amd64/qsub -V -cwd -l m_mem_free=3G -v LENGTH=$LENGTH -v SIZE=$size -v TYPE=bwa -v IN=$IN /seq/schatz/mschatz/ginkgo/genomes/scripts/binBWA
done

touch bwa_done

