#!/bin/bash

SCRIPTS=/seq/schatz/mschatz/ginkgo/genomes/scripts

#Concatenate chromsome intervals
echo -e "CHR\tEND" > variable_${SIZE}_${LENGTH}_${TYPE}
cat `ls | grep results_${SIZE}_${LENGTH}_${TYPE} | sort -V` >> variable_${SIZE}_${LENGTH}_${TYPE}

#rm -f results*

#Generate interval boundaries
$SCRIPTS/bounds variable_${SIZE}_${LENGTH}_${TYPE} bounds_variable_${SIZE}_${LENGTH}_${TYPE}

#Calculate GC content in intervals
$SCRIPTS/GC variable_${SIZE}_${LENGTH}_${TYPE} GC_variable_${SIZE}_${LENGTH}_${TYPE} lengths

#Generate gene files
$SCRIPTS/match_genes_to_bins variable_${SIZE}_${LENGTH}_${TYPE} genes genes_variable_${SIZE}_${LENGTH}_${TYPE}

echo -e "\nFinished"
