#!/bin/bash

###TO CHECK
###1 - If user specifies facs file, "facs" variable is not set...

## == Setup variables ===============================
home=/mnt/data/ginkgo
dir=${home}/uploads/${1}
source ${dir}/config
distMet=$distMeth

inFile=list
statFile=status.xml
genome=${home}/genomes/${chosen_genome}

## == Analysis ===========================================


############################################################
########## Error Check and Reformat User Files #############
############################################################

if [ "$f" == "0" ]; then
  touch ${dir}/ploidyDummy.txt
  facs=ploidyDummy.txt
else 
  sed "s/.bed//g" ${dir}/${facs} | sort -k1,1 | awk '{print $1"\t"$2}' > ${dir}/quickTemp 
  mv ${dir}/quickTemp ${dir}/${facs}
fi


############################################################
####### Map Reads & Prepare Samples For Processing #########
############################################################

total=`wc -l < ${dir}/${inFile}`

if [ "$init" == "1" ]; then

  cnt=0;
  
  #Clean directory
  rm -f ${dir}/*_mapped ${dir}/*.jpeg ${dir}/*.newick ${dir}/*.xml ${dir}/Seg*

  #Map user bed files to appropriate bins
  while read file; do
    ${home}/scripts/status ${dir}/${statFile} 1 $file $cnt $total 
    ${home}/scripts/binUnsorted ${genome}/${binMeth} `wc -l < ${genome}/${binMeth}` ${dir}/${file} `echo ${file} | sed "s/.bed//g"` ${dir}/${file}_mapped
    #${home}/binUnsorted ${genome}/fixed_1000 `wc -l < ${genome}/fixed_1000` ${dir}/${file} `echo ${file} | sed "s/.bed//g"` ${dir}/${file}_binned
    cnt=$(($cnt+1));
  done < ${dir}/${inFile}

  #Concatenate binned reads to central file  
  paste ${dir}/*_mapped > ${dir}/data

  #Generate statistics
  ${home}/scripts/stats.R $dir $statFile ${dir}/data
  rm -f ${dir}/*_mapped ${dir}/*_binned

  #Map reference sample (if provided by user)
  if [ "$segMeth" == "2" ]; then
    ${home}/scripts/binUnsorted ${genome}/${binMeth} `wc -l < ${genome}/${binMeth}` ${dir}/${ref} Reference ${dir}/${ref}_mapped
  else
    ref=refDummy.bed
    touch ${dir}/${ref}_mapped
  fi

fi


############################################################
######### Run Mapped Data Through Primary Pipeline #########
############################################################

if [ "$process" == "1" ]; then
  ${home}/scripts/status ${dir}/${statFile} 3 Initializing 0 1
  ${home}/scripts/interval ${genome}/genes ${dir}/${query} ${dir}/intervals.txt
  ${home}/scripts/process.R $genome $dir $statFile data $segMeth $binMeth $clustMeth $distMet ${dir}/${query} ${ref}_mapped $f $facs
fi


############################################################
#### Recreate Clusters/Heat Maps (With New Parameters) #####
############################################################

if [ "$fix" == "1" ]; then
  ${home}/scripts/reclust.R $dir $statFile SegFile $clustMeth $distMet $f $facs
fi


############################################################
#### Recreate CN Profile (With New Gene/Interval Query) ####
############################################################

if [ "$q" == "1" ] && [ "$process" == "0" ]; then
  ${home}/scripts/interval ${genome}/genes ${dir}/${query} ${dir}/intervals.txt
  ${home}/scripts/queryAll.R $genome $dir $statFile $binMeth ${dir}/${query} $f
fi

if [ "$email" != "" ]; then
	echo -e "Your analysis on Ginkgo is complete! Check out your results at $permalink" | mail -s "Your Analysis Results" $email -- -F "Ginkgo"
fi
